### ISSUE TITLE
Error running the example CUDA error 

### ISSUE THREAD

**Issue by yhqqxq** [jy0205/Pyramid-Flow#118]
I encountered this error on Windows, how can I solve it?

-------------------------------------------------------------------------
[INFO] Model initialized successfully.
[INFO] Starting text-to-video generation...
[INFO] Starting text-to-video generation...
[ERROR] Error during text-to-video generation: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "G:\AI\AI\tool\Pyramid-Flow\env\lib\site-packages\gradio\queueing.py", line 622, in process_events
    response = await route_utils.call_process_api(
  File "G:\AI\AI\tool\Pyramid-Flow\env\lib\site-packages\gradio\route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
  File "G:\AI\AI\tool\Pyramid-Flow\env\lib\site-packages\gradio\blocks.py", line 2024, in process_api
    data = await self.postprocess_data(block_fn, result["prediction"], state)
  File "G:\AI\AI\tool\Pyramid-Flow\env\lib\site-packages\gradio\blocks.py", line 1832, in postprocess_data
    outputs_cached = await processing_utils.async_move_files_to_cache(
  File "G:\AI\AI\tool\Pyramid-Flow\env\lib\site-packages\gradio\processing_utils.py", line 703, in async_move_files_to_cache
    return await client_utils.async_traverse(
  File "G:\AI\AI\tool\Pyramid-Flow\env\lib\site-packages\gradio_client\utils.py", line 1023, in async_traverse
    new_obj[key] = await async_traverse(value, func, is_root)
  File "G:\AI\AI\tool\Pyramid-Flow\env\lib\site-packages\gradio_client\utils.py", line 1019, in async_traverse
    return await func(json_obj)
  File "G:\AI\AI\tool\Pyramid-Flow\env\lib\site-packages\gradio\processing_utils.py", line 676, in _move_to_cache
    temp_file_path = await block.async_move_resource_to_block_cache(
  File "G:\AI\AI\tool\Pyramid-Flow\env\lib\site-packages\gradio\blocks.py", line 312, in async_move_resource_to_block_cache
    temp_file_path = processing_utils.save_file_to_cache(
  File "G:\AI\AI\tool\Pyramid-Flow\env\lib\site-packages\gradio\processing_utils.py", line 277, in save_file_to_cache
    temp_dir = hash_file(file_path)
  File "G:\AI\AI\tool\Pyramid-Flow\env\lib\site-packages\gradio\processing_utils.py", line 206, in hash_file
    with open(file_path, "rb") as f:
OSError: [Errno 22] Invalid argument: 'G:\\AI\\AI\\tool\\Pyramid-Flow\\Error during video generation: CUDA error: invalid argument\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n'

**Comment by feifeiobama** [comment]
This seems to be an error due to the environment not being compiled with CUDA. Please follow https://pytorch.org/get-started/previous-versions/ to install PyTorch 2.1.2 with CUDA support.
