### ISSUE TITLE
Building project locally, or via Colab

### ISSUE THREAD

**Issue by MyCroniesSoft** [jy0205/Pyramid-Flow#129]
Hello after running this bat file:
Runs straight out of the box on a 4090, overall time for 10 seconds on a 4930k 10 year old cpu, and horrific specs about 6 minutes to 11 minutes, the code cannot exceed 10 seconds, after experimentation, or stitching the outcomes not like stability ai svd video model, where adding in the last frame back into the model once its ready, the image generated from that has lost its original source, so hypothetically speaking using something like midway to generate a video, then cut the last frame and add it back into stability ai, sure it would work. however there would be a water mark, and the overall experience would not be pleasant but if depserate there's that too.

So the bat file just needs to be created in a text file, copy everything below, and save then run, don't expect miracles, the requirments.txt file will need the information updated, so go below the comment, search for requirements.txt copy it over to the built requirements.txt file and you will be able to start running, don't ask why it's like that.

Happy travels on your ai journey.

You're free to do the same if reading from off site:

Myfile.bat
-------------------Copy into text file----below-------save--------------run--
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
@echo off
REM Create and activate virtual environment
python -m venv venv
call venv\Scripts\activate

REM Upgrade pip
python -m pip install --upgrade pip

REM Clone Pyramid Flow repository
git clone https://github.com/jy0205/Pyramid-Flow.git
cd Pyramid-Flow

REM Uninstall existing Torch
pip uninstall -y torch

REM Install CUDA toolkit (ensure CUDA is installed on your system)
REM You can download CUDA from https://developer.nvidia.com/cuda-downloads

REM Install Torch with CUDA support
pip install torch==2.1.2+cu121 -f https://download.pytorch.org/whl/cu121/torch_stable.html

REM Install compatible version of torchvision
pip install torchvision==0.16.0+cu121 -f https://download.pytorch.org/whl/cu121/torch_stable.html

REM Install other required dependencies
pip install xformers
pip install gradio
pip install -r requirements.txt

REM Verify CUDA availability
python -c "import torch; print(torch.cuda.is_available())"

REM Run Pyramid Flow
python app.py

REM Deactivate virtual environment
deactivate

-------------------------------------------------------------------------
-----Already been solved, if you get this error, just go to the first comment below.-------

Now the problems, this was tested on windows, not linux bash, or if possible on apple os.

Issues in commadline:
--------------------------------------------------------------------

 copying xformers\_flash_attn\ops\triton\__init__.py -> build\lib.win-amd64-cpython-310\xformers\_flash_attn\ops\triton
      running build_ext
      Z:\Projects\venv\lib\site-packages\torch\utils\cpp_extension.py:383: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      Z:\Projects\venv\lib\site-packages\torch\utils\cpp_extension.py:414: UserWarning: The detected CUDA version (12.6) has a minor version mismatch with the version that was used to compile PyTorch (12.1). Most likely this shouldn't be a problem.
        warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
      building 'xformers._C_flashattention' extension
      creating C:\Users\Coder\AppData\Local\Temp\pip-install-b98ljr7f\xformers_9b1c5faebea24bfc841f0b79ba3b2426\build\temp.win-amd64-cpython-310
      creating C:\Users\Coder\AppData\Local\Temp\pip-install-b98ljr7f\xformers_9b1c5faebea24bfc841f0b79ba3b2426\build\temp.win-amd64-cpython-310\Release
      creating C:\Users\Coder\AppData\Local\Temp\pip-install-b98ljr7f\xformers_9b1c5faebea24bfc841f0b79ba3b2426\build\temp.win-amd64-cpython-310\Release\Users
      creating C:\Users\Coder\AppData\Local\Temp\pip-install-b98ljr7f\xformers_9b1c5faebea24bfc841f0b79ba3b2426\build\temp.win-amd64-cpython-310\Release\Users\Coder
      creating C:\Users\Coder\AppData\Local\Temp\pip-install-b98ljr7f\xformers_9b1c5faebea24bfc841f0b79ba3b2426\build\temp.win-amd64-cpython-310\Release\Users\Coder\AppData
      creating C:\Users\Coder\AppData\Local\Temp\pip-install-b98ljr7f\xformers_9b1c5faebea24bfc841f0b79ba3b2426\build\temp.win-amd64-cpython-310\Release\Users\Coder\AppData\Local
      creating C:\Users\Coder\AppData\Local\Temp\pip-install-b98ljr7f\xformers_9b1c5faebea24bfc841f0b79ba3b2426\build\temp.win-amd64-cpython-310\Release\Users\Coder\AppData\Local\Temp
      creating C:\Users\Coder\AppData\Local\Temp\pip-install-b98ljr7f\xformers_9b1c5faebea24bfc841f0b79ba3b2426\build\temp.win-amd64-cpython-310\Release\Users\Coder\AppData\Local\Temp\pip-install-b98ljr7f
      creating C:\Users\Coder\AppData\Local\Temp\pip-install-b98ljr7f\xformers_9b1c5faebea24bfc841f0b79ba3b2426\build\temp.win-amd64-cpython-310\Release\Users\Coder\AppData\Local\Temp\pip-install-b98ljr7f\xformers_9b1c5faebea24bfc841f0b79ba3b2426
      creating C:\Users\Coder\AppData\Local\Temp\pip-install-b98ljr7f\xformers_9b1c5faebea24bfc841f0b79ba3b2426\build\temp.win-amd64-cpython-310\Release\Users\Coder\AppData\Local\Temp\pip-install-b98ljr7f\xformers_9b1c5faebea24bfc841f0b79ba3b2426\third_party
      creating C:\Users\Coder\AppData\Local\Temp\pip-install-b98ljr7f\xformers_9b1c5faebea24bfc841f0b79ba3b2426\build\temp.win-amd64-cpython-310\Release\Users\Coder\AppData\Local\Temp\pip-install-b98ljr7f\xformers_9b1c5faebea24bfc841f0b79ba3b2426\third_party\flash-attention
      creating C:\Users\Coder\AppData\Local\Temp\pip-install-b98ljr7f\xformers_9b1c5faebea24bfc841f0b79ba3b2426\build\temp.win-amd64-cpython-310\Release\Users\Coder\AppData\Local\Temp\pip-install-b98ljr7f\xformers_9b1c5faebea24bfc841f0b79ba3b2426\third_party\flash-attention\csrc
      creating C:\Users\Coder\AppData\Local\Temp\pip-install-b98ljr7f\xformers_9b1c5faebea24bfc841f0b79ba3b2426\build\temp.win-amd64-cpython-310\Release\Users\Coder\AppData\Local\Temp\pip-install-b98ljr7f\xformers_9b1c5faebea24bfc841f0b79ba3b2426\third_party\flash-attention\csrc\flash_attn
      creating C:\Users\Coder\AppData\Local\Temp\pip-install-b98ljr7f\xformers_9b1c5faebea24bfc841f0b79ba3b2426\build\temp.win-amd64-cpython-310\Release\Users\Coder\AppData\Local\Temp\pip-install-b98ljr7f\xformers_9b1c5faebea24bfc841f0b79ba3b2426\third_party\flash-attention\csrc\flash_attn\src
      Emitting ninja build file C:\Users\Coder\AppData\Local\Temp\pip-install-b98ljr7f\xformers_9b1c5faebea24bfc841f0b79ba3b2426\build\temp.win-amd64-cpython-310\Release\build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      ninja: error: Stat(C:/Users/Coder/AppData/Local/Temp/pip-install-b98ljr7f/xformers_9b1c5faebea24bfc841f0b79ba3b2426/build/temp.win-amd64-cpython-310/Release/Users/Coder/AppData/Local/Temp/pip-install-b98ljr7f/xformers_9b1c5faebea24bfc841f0b79ba3b2426/third_party/flash-attention/csrc/flash_attn/flash_api.obj): Filename longer than 260 characters
      Traceback (most recent call last):
        File "Z:\Projects\venv\lib\site-packages\torch\utils\cpp_extension.py", line 2100, in _run_ninja_build
          subprocess.run(
        File "C:\Python310\lib\subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Coder\AppData\Local\Temp\pip-install-b98ljr7f\xformers_9b1c5faebea24bfc841f0b79ba3b2426\setup.py", line 680, in <module>
          setuptools.setup(
        File "Z:\Projects\venv\lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "Z:\Projects\venv\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "Z:\Projects\venv\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "Z:\Projects\venv\lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "Z:\Projects\venv\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "Z:\Projects\venv\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "Z:\Projects\venv\lib\site-packages\wheel\_bdist_wheel.py", line 378, in run
          self.run_command("build")
        File "Z:\Projects\venv\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "Z:\Projects\venv\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "Z:\Projects\venv\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "Z:\Projects\venv\lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "Z:\Projects\venv\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "Z:\Projects\venv\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "Z:\Projects\venv\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "Z:\Projects\venv\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "Z:\Projects\venv\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
          self.build_extensions()
        File "C:\Users\Coder\AppData\Local\Temp\pip-install-b98ljr7f\xformers_9b1c5faebea24bfc841f0b79ba3b2426\setup.py", line 637, in build_extensions
          super().build_extensions()
        File "Z:\Projects\venv\lib\site-packages\torch\utils\cpp_extension.py", line 873, in build_extensions
          build_ext.build_extensions(self)
        File "Z:\Projects\venv\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 466, in build_extensions
          self._build_extensions_serial()
        File "Z:\Projects\venv\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 492, in _build_extensions_serial
          self.build_extension(ext)
        File "Z:\Projects\venv\lib\site-packages\setuptools\command\build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "Z:\Projects\venv\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 547, in build_extension
          objects = self.compiler.compile(
        File "Z:\Projects\venv\lib\site-packages\torch\utils\cpp_extension.py", line 845, in win_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "Z:\Projects\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1774, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "Z:\Projects\venv\lib\site-packages\torch\utils\cpp_extension.py", line 2116, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for xformers
  Running setup.py clean for xformers
Failed to build xformers
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (xformers)

Second issue------------------------------------

Will cache examples in 'Z:\Projects\Pyramid-Flow\.gradio\cached_examples\28' directory at first use.

INFO: Could not find files for the given pattern(s).
* Running on local URL:  http://127.0.0.1:7860
* Running on public URL: https://29a0.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)
[DEBUG] generate_text_to_video called.
[INFO] Initializing model with variant='768p', using bf16 precision...
[DEBUG] Model base path: Z:\Projects\Pyramid-Flow\pyramid_flow_model
using half precision
Using temporal causal attention
We interp the position embedding of condition latents
You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 2/2 [01:11<00:00, 35.53s/it]
The latent dimmension channes is 16
The start sigmas and end sigmas of each stage is Start: {0: 1.0, 1: 0.8002399489209289, 2: 0.5007496155411024}, End: {0: 0.6669999957084656, 1: 0.33399999141693115, 2: 0.0}, Ori_start: {0: 1.0, 1: 0.6669999957084656, 2: 0.33399999141693115}
[WARNING] CUDA is not available. Proceeding without GPU.
[INFO] Model initialized successfully.
[INFO] Starting text-to-video generation...
Z:\Projects\venv\lib\site-packages\torch\amp\autocast_mode.py:250: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn(
[ERROR] Error during text-to-video generation: Torch not compiled with CUDA enabled
Traceback (most recent call last):
  File "Z:\Projects\venv\lib\site-packages\gradio\queueing.py", line 703, in process_events
    response = await route_utils.call_process_api(
  File "Z:\Projects\venv\lib\site-packages\gradio\route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
  File "Z:\Projects\venv\lib\site-packages\gradio\blocks.py", line 2014, in process_api
    result = await self.call_function(
  File "Z:\Projects\venv\lib\site-packages\gradio\blocks.py", line 1579, in call_function
    prediction = await utils.async_iteration(iterator)
  File "Z:\Projects\venv\lib\site-packages\gradio\utils.py", line 691, in async_iteration
    return await anext(iterator)
  File "Z:\Projects\venv\lib\site-packages\gradio\utils.py", line 685, in __anext__
    return await anyio.to_thread.run_sync(
  File "Z:\Projects\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "Z:\Projects\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "Z:\Projects\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "Z:\Projects\venv\lib\site-packages\gradio\utils.py", line 668, in run_sync_iterator_async
    return next(iterator)
  File "Z:\Projects\venv\lib\site-packages\gradio\utils.py", line 829, in gen_wrapper
    response = next(iterator)
  File "Z:\Projects\venv\lib\site-packages\gradio\helpers.py", line 494, in sync_lazy_cache
    self.cache_logger.flag(output)
  File "Z:\Projects\venv\lib\site-packages\gradio\flagging.py", line 321, in flag
    component.flag(sample, flag_dir=save_dir)
  File "Z:\Projects\venv\lib\site-packages\gradio\components\base.py", line 354, in flag
    payload = payload.copy_to_dir(flag_dir).model_dump()
  File "Z:\Projects\venv\lib\site-packages\gradio\data_classes.py", line 163, in copy_to_dir
    x=traverse(
  File "Z:\Projects\venv\lib\site-packages\gradio_client\utils.py", line 999, in traverse
    new_obj[key] = traverse(value, func, is_root)
  File "Z:\Projects\venv\lib\site-packages\gradio_client\utils.py", line 995, in traverse
    return func(json_obj)
  File "Z:\Projects\venv\lib\site-packages\gradio\data_classes.py", line 158, in unique_copy
    return data._copy_to_dir(
  File "Z:\Projects\venv\lib\site-packages\gradio\data_classes.py", line 280, in _copy_to_dir
    new_name = shutil.copy(self.path, dir)
  File "C:\Python310\lib\shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Python310\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'Z:\\Projects\\Pyramid-Flow\\Error during video generation: Torch not compiled with CUDA enabled'

-------------------------Any-----------solutions-----------can----------be----------added------------------below---------------------

**Comment by feifeiobama** [comment]
There is an installation error related to the CUDA version. For users with CUDA 12.6, we recommend installing a newer PyTorch version that is compatible with it. Please see https://huggingface.co/spaces/Pyramid-Flow/pyramid-flow/tree/main for the `requirements.txt`. 

However, newer PyTorch versions may have a problem with multivariate Gaussian sampling, please refer to https://github.com/jy0205/Pyramid-Flow/issues/121 if you encounter this problem.
