### ISSUE TITLE
Gradio app not working with minifux models

### ISSUE THREAD

**Issue by zelenooki87** [jy0205/Pyramid-Flow#139]
Running on local URL:  http://127.0.0.1:7860

Could not create share link. Please check your internet connection or our status page: https://status.gradio.app.
[DEBUG] generate_text_to_video called.
[INFO] Initializing model with variant='768p', using bf16 precision...
[DEBUG] Model base path: C:\Users\Miki\Pyramid-Flow\pyramid_flow_model
[ERROR] config.json not found in 'C:\Users\Miki\Pyramid-Flow\pyramid_flow_model\diffusion_transformer_768p'.
[ERROR] Model initialization failed: config.json not found in 'C:\Users\Miki\Pyramid-Flow\pyramid_flow_model\diffusion_transformer_768p'.
Traceback (most recent call last):
  File "C:\Users\Miki\anaconda3\envs\pyramid\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\Miki\anaconda3\envs\pyramid\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\Miki\anaconda3\envs\pyramid\lib\site-packages\gradio\blocks.py", line 1945, in process_api
    data = await self.postprocess_data(block_fn, result["prediction"], state)
  File "C:\Users\Miki\anaconda3\envs\pyramid\lib\site-packages\gradio\blocks.py", line 1770, in postprocess_data
    outputs_cached = await processing_utils.async_move_files_to_cache(
  File "C:\Users\Miki\anaconda3\envs\pyramid\lib\site-packages\gradio\processing_utils.py", line 485, in async_move_files_to_cache
    return await client_utils.async_traverse(
  File "C:\Users\Miki\anaconda3\envs\pyramid\lib\site-packages\gradio_client\utils.py", line 1003, in async_traverse
    new_obj[key] = await async_traverse(value, func, is_root)
  File "C:\Users\Miki\anaconda3\envs\pyramid\lib\site-packages\gradio_client\utils.py", line 999, in async_traverse
    return await func(json_obj)
  File "C:\Users\Miki\anaconda3\envs\pyramid\lib\site-packages\gradio\processing_utils.py", line 460, in _move_to_cache
    temp_file_path = await block.async_move_resource_to_block_cache(
  File "C:\Users\Miki\anaconda3\envs\pyramid\lib\site-packages\gradio\blocks.py", line 308, in async_move_resource_to_block_cache
    temp_file_path = processing_utils.save_file_to_cache(
  File "C:\Users\Miki\anaconda3\envs\pyramid\lib\site-packages\gradio\processing_utils.py", line 250, in save_file_to_cache
    temp_dir = hash_file(file_path)
  File "C:\Users\Miki\anaconda3\envs\pyramid\lib\site-packages\gradio\processing_utils.py", line 182, in hash_file
    with open(file_path, "rb") as f:
OSError: [Errno 22] Invalid argument: "C:\\Users\\Miki\\Pyramid-Flow\\Model initialization failed: config.json not found in 'C:\\Users\\Miki\\Pyramid-Flow\\pyramid_flow_model\\diffusion_transformer_768p'"

**Comment by jy0205** [comment]
Hi, we have fixed this bug. By the way, make sure to download the latest model version from the huggingface (https://huggingface.co/rain1011/pyramid-flow-miniflux), since we have updated the 384p checkpoint not long ago.
