### ISSUE TITLE
NumPy 1.x/2.0 Mismatch - Cannot build environment in Windows or WSL

### ISSUE THREAD

**Issue by purzbeats** [jy0205/Pyramid-Flow#3]
(env) C:\ai\Pyramid-Flow>python ./gen.py

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\ai\Pyramid-Flow\gen.py", line 1, in <module>
    import torch
  File "C:\ai\Pyramid-Flow\env\lib\site-packages\torch\__init__.py", line 1382, in <module>
    from .functional import *  # noqa: F403
  File "C:\ai\Pyramid-Flow\env\lib\site-packages\torch\functional.py", line 7, in <module>
    import torch.nn.functional as F
  File "C:\ai\Pyramid-Flow\env\lib\site-packages\torch\nn\__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "C:\ai\Pyramid-Flow\env\lib\site-packages\torch\nn\modules\__init__.py", line 35, in <module>
    from .transformer import TransformerEncoder, TransformerDecoder, \
  File "C:\ai\Pyramid-Flow\env\lib\site-packages\torch\nn\modules\transformer.py", line 20, in <module>
    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
C:\ai\Pyramid-Flow\env\lib\site-packages\torch\nn\modules\transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
Please install flash attention
Traceback (most recent call last):
  File "C:\ai\Pyramid-Flow\gen.py", line 6, in <module>
    torch.cuda.set_device(0)
  File "C:\ai\Pyramid-Flow\env\lib\site-packages\torch\cuda\__init__.py", line 404, in set_device
    torch._C._cuda_setDevice(device)
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

**Comment by purzbeats** [comment]
Fixed it, two problems, I didn't have torch installed, and I had to downgrade numpy, hopefully this helps.

`pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121`
`pip install --upgrade numpy==1.26.4`

**Comment by jy0205** [comment]
Thanks for your efforts! We have updated the Numpy version requirement.
