### ISSUE TITLE
Error when installation

### ISSUE THREAD

**Issue by chikiuso** [jy0205/Pyramid-Flow#30]
Hi, I keep having the error message when I tried to run pip3 install -r requirements.txt, do you have any idea how to fix it? thanks!

ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 357, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 281, in _get_abstract_dist_for
    req.populate_link(self.finder, upgrade_allowed, require_hashes)
  File "/usr/lib/python3/dist-packages/pip/_internal/req/req_install.py", line 249, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/_internal/index/package_finder.py", line 898, in find_requirement
    best_candidate_result = self.find_best_candidate(
  File "/usr/lib/python3/dist-packages/pip/_internal/index/package_finder.py", line 881, in find_best_candidate
    candidates = self.find_all_candidates(project_name)
  File "/usr/lib/python3/dist-packages/pip/_internal/index/package_finder.py", line 825, in find_all_candidates
    package_links = self.process_project_url(
  File "/usr/lib/python3/dist-packages/pip/_internal/index/package_finder.py", line 797, in process_project_url
    package_links = self.evaluate_links(
  File "/usr/lib/python3/dist-packages/pip/_internal/index/package_finder.py", line 779, in evaluate_links
    candidate = self.get_install_candidate(link_evaluator, link)
  File "/usr/lib/python3/dist-packages/pip/_internal/index/package_finder.py", line 764, in get_install_candidate
    return InstallationCandidate(
  File "/usr/lib/python3/dist-packages/pip/_internal/models/candidate.py", line 18, in __init__
    self.version = parse_version(version)  # type: _BaseVersion
  File "/usr/local/lib/python3.8/dist-packages/packaging/version.py", line 56, in parse
    return Version(version)
  File "/usr/local/lib/python3.8/dist-packages/packaging/version.py", line 202, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '1.1-linux32'

**Comment by jy0205** [comment]
Thanks for your attention! You can refer to https://github.com/jy0205/Pyramid-Flow/issues/29#issuecomment-2407016291 and https://github.com/jy0205/Pyramid-Flow/issues/22#issuecomment-2406422182 and try again?

**Comment by georgitsenov** [comment]
> Thanks for your attention! You can refer to [#29 (comment)](https://github.com/jy0205/Pyramid-Flow/issues/29#issuecomment-2407016291) and [#22 (comment)](https://github.com/jy0205/Pyramid-Flow/issues/22#issuecomment-2406422182) and try again?

To start app.py additionally to https://huggingface.co/spaces/Pyramid-Flow/pyramid-flow/, install pre-requirements.txt and requirements.txt you need to have your virtual env initialized with python 3.10 plus gradio and spaces (with python 3.9 gradio version is too low and app.py cannot start).

**Comment by MakingMadness** [comment]
The installation instructions specifically say "conda create -n pyramid python==3.8.10", is this a mistake?

**Comment by feifeiobama** [comment]
> The installation instructions specifically say "conda create -n pyramid python==3.8.10", is this a mistake?

No, this is just our default environment. I think the current version of the codebase (after https://github.com/jy0205/Pyramid-Flow/pull/39) supports a wider range of Python, PyTorch, and NumPy versions, so please use it more freely.

**Comment by merthmagic** [comment]
> The installation instructions specifically say "conda create -n pyramid python==3.8.10", is this a mistake?

I also met some error messages during the dependencies installation period, seems python 3.11 will work

**Comment by merthmagic** [comment]
> > The installation instructions specifically say "conda create -n pyramid python==3.8.10", is this a mistake?
> 
> I also met some error messages during the dependencies installation period, seems python 3.11 will work

Withdraw the previous reply, I met another error(it's related to package `thinc`) with `python 3.11` , `ubuntu 22.04`

**Comment by feifeiobama** [comment]
> > > The installation instructions specifically say "conda create -n pyramid python==3.8.10", is this a mistake?
> > 
> > 
> > I also met some error messages during the dependencies installation period, seems python 3.11 will work
> 
> Withdraw the previous reply, I met another error(it's related to package `thinc`) with `python 3.11` , `ubuntu 22.04`

It appears that this issue has been addressed in https://github.com/jy0205/Pyramid-Flow/pull/44. Thanks @merthmagic for the fix.
