### ISSUE TITLE
TypeError: expected np.ndarray (got Tensor)

### ISSUE THREAD

**Issue by ruapotato** [jy0205/Pyramid-Flow#40]
Running:
```
from huggingface_hub import snapshot_download
import torch
from PIL import Image
from pyramid_dit import PyramidDiTForVideoGeneration
from diffusers.utils import load_image, export_to_video


model_path = '/home/david/.cache/huggingface/hub/pyramid-flow'   # The local directory to save downloaded checkpoint
snapshot_download("rain1011/pyramid-flow-sd3", local_dir=model_path, local_dir_use_symlinks=False, repo_type='model')


torch.cuda.set_device(0)
model_dtype, torch_dtype = 'bf16', torch.bfloat16   # Use bf16 (not support fp16 yet)

model = PyramidDiTForVideoGeneration(
    '/home/david/.cache/huggingface/hub/pyramid-flow',                                         # The downloaded checkpoint dir
    model_dtype,
    model_variant='diffusion_transformer_384p',     # 'diffusion_transformer_384p'
    save_memory=True,
)

model.vae.to("cuda")
model.dit.to("cuda")
model.text_encoder.to("cuda")
model.vae.enable_tiling()


# Clear CUDA cache
torch.cuda.empty_cache()

prompt = "The GNU wildebeest leaping through a neural network, leaving trails of open-source code."

with torch.no_grad(), torch.amp.autocast(device_type='cuda', dtype=torch.bfloat16):
    frames = model.generate(
        prompt=prompt,
        num_inference_steps=[20, 20, 20],
        video_num_inference_steps=[10, 10, 10],
        height=384,
        width=640,
        temp=16,
        guidance_scale=9.0,
        video_guidance_scale=5.0,
        output_type="pil",
        save_memory=True,
    )

export_to_video(frames, "./text_to_video_sample.mp4", fps=24)

```
I get this error:
```
(pyenv) david@davidmain:~/myProjects/AI/BIN/Pyramid-Flow$ python ./main.py
/matrix/david/main_home_folder/myProjects/AI/BIN/Pyramid-Flow/pyenv/lib/python3.11/site-packages/huggingface_hub/file_download.py:1204: UserWarning: `local_dir_use_symlinks` parameter is deprecated and will be ignored. The process to download files to a local folder has been updated and do not rely on symlinks anymore. You only need to pass a destination folder as`local_dir`.
For more details, check out https://huggingface.co/docs/huggingface_hub/main/en/guides/download#download-files-to-local-folder.
  warnings.warn(
Fetching 29 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 29/29 [00:00<00:00, 2941.16it/s]
using half precision
Using temporal causal attention
We interp the position embedding of condition latents
You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:06<00:00,  3.05s/it]
The latent dimmension channes is 16
Traceback (most recent call last):
  File "/matrix/david/main_home_folder/myProjects/AI/BIN/Pyramid-Flow/./main.py", line 15, in <module>
    model = PyramidDiTForVideoGeneration(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/matrix/david/main_home_folder/myProjects/AI/BIN/Pyramid-Flow/pyramid_dit/pyramid_dit_for_video_gen_pipeline.py", line 129, in __init__
    self.scheduler = PyramidFlowMatchEulerDiscreteScheduler(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/matrix/david/main_home_folder/myProjects/AI/BIN/Pyramid-Flow/pyenv/lib/python3.11/site-packages/diffusers/configuration_utils.py", line 653, in inner_init
    init(self, *args, **init_kwargs)
  File "/matrix/david/main_home_folder/myProjects/AI/BIN/Pyramid-Flow/diffusion_schedulers/scheduling_flow_matching.py", line 66, in __init__
    self.init_sigmas_for_each_stage()
  File "/matrix/david/main_home_folder/myProjects/AI/BIN/Pyramid-Flow/diffusion_schedulers/scheduling_flow_matching.py", line 146, in init_sigmas_for_each_stage
    self.timesteps_per_stage[i_s] = torch.from_numpy(timesteps[:-1])
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected np.ndarray (got Tensor)
```
This is running on Debian 12.
```
(pyenv) david@davidmain:~/myProjects/AI/BIN/Pyramid-Flow$ pip list
Package                  Version
------------------------ ----------
accelerate               1.0.0
asttokens                2.4.1
certifi                  2024.8.30
charset-normalizer       3.4.0
decorator                5.1.1
diffusers                0.30.3
einops                   0.8.0
executing                2.1.0
filelock                 3.16.1
fsspec                   2024.9.0
huggingface-hub          0.25.2
idna                     3.10
importlib_metadata       8.5.0
ipython                  8.28.0
jedi                     0.19.1
Jinja2                   3.1.4
MarkupSafe               3.0.1
matplotlib-inline        0.1.7
mpmath                   1.3.0
networkx                 3.4
numpy                    2.1.2
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        9.1.0.70
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.20.5
nvidia-nvjitlink-cu12    12.6.77
nvidia-nvtx-cu12         12.1.105
opencv-python            4.10.0.84
packaging                24.1
parso                    0.8.4
pexpect                  4.9.0
pillow                   10.4.0
pip                      23.0.1
prompt_toolkit           3.0.48
protobuf                 5.28.2
psutil                   6.0.0
ptyprocess               0.7.0
pure_eval                0.2.3
Pygments                 2.18.0
PyYAML                   6.0.2
regex                    2024.9.11
requests                 2.32.3
safetensors              0.4.5
sentencepiece            0.2.0
setuptools               66.1.1
six                      1.16.0
stack-data               0.6.3
sympy                    1.13.3
tensorboardX             2.6.2.2
timm                     1.0.9
tokenizers               0.20.1
torch                    2.4.1
torchvision              0.19.1
tqdm                     4.66.5
traitlets                5.14.3
transformers             4.45.2
triton                   3.0.0
typing_extensions        4.12.2
urllib3                  2.2.3
wcwidth                  0.2.13
zipp                     3.20.2
```
The workaround is in pull request #39

**Comment by feifeiobama** [comment]
Thanks for providing a workaround. The pull request has been merged to the main branch.
